baseUrl = "http://juancgalan.com/"
languageCode = "en-us"
title = "Dr. Juan Carlos Galán Hernández"
theme = "hugo-strata"
publishDir = "public"

paginate = 10

[params]
	name = "Juan Carlos Galán Hernández"
	description = "Personal Web Site"
	date_format = "2006-01-02"
	
	custom_js = []
	custom_css = []
	

	[params.sidebar]
		avatar = "avatar.png"
		bio = "**Dr. Juan Carlos Galán Hernández** <p> Researcher, Writer, Game Designer,<br> Programming Languages Enthusiast.</p>"
		twitter = "zenathark"
		github = "zenathark"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		
		copyright = [
			"Created by Juan Carlos Galán Hernández",
			"Theme based on [Strata](https://github.com/digitalcraftsman/hugo-strata-theme)",
			"Original background by [Jesse Vincent](https://fsck.com/)",
			"Powered by [Hugo](http://gohugo.io)",
			"Hosted by [Github](http://pages.github.com)",
			"Content of this site is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)",
			"Code is licensed under [MIT License](https://opensource.org/licenses/mit-license.html)"
			
		]
	
	[params.about]
		hide = false
		title = "Welcome!"
		content = "Welcome to my personal page. <br><br> Here you will find some of my research about Programming Languages, Game Design and Signal Processing. And some times I will also ramble about progamming tools and anime.<br> Feel free to look around. <blockquote> The language in which we express our ideas has a strong influence on our thought processes. <br> - Donald Ervin Knuth, Literate Programming </blockquote>"

	[params.portfolio]
		hide = true
		title = "Publications"
		
		[[params.portfolio.gallery]]
			title = "<a href="#"> Lorem ipsum </a>"
			description = "laralalala"

	[params.contact]
		hide = false
		title = "Get In Touch"
		# content = "UAOEUOEUAIOUAE"

		address = [
			"Room LA202",
			"Universidad de las Américas Puebla",
		        "Sta. Catarina Martir",
		        "San Andres Cholula, Puebla, C.P. 72810",
			"Mexico"
                ]

		email = "juan.galan@udlap.mx"

		[params.contact.form]
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 0

[[menu.main]]
	name = "Writer's Journal"
	url = "post/"
	weight = 60 

[[menu.main]]
	name = "About This Site"
	url = "about/"
	weight = 10

[[menu.main]]
	name = "About Me"
	url = "resume/"
	weight = 20

[[menu.main]]
	name = "Writing Project #1"
	url = "wp1/"
	weight = 30

[[menu.main]]
	name = "Writing Project #2"
	url = "wp2/"
	weight = 40

[[menu.main]]
	name = "Writing Project #3"
	url = "wp3/"
	weight = 50
