baseUrl = "http://juancgalan.com/"
languageCode = "en-us"
title = "Hugo identity"
theme = "hugo-strata"
publishDir = "public"

paginate = 10

[params]
	name = "Juan Carlos Gal치n Hern치ndez"
	description = "Personal Web Site"
	date_format = "2006-01-02"
	
	custom_js = []
	custom_css = []
	

	[params.sidebar]
		avatar = "avatar.png"
		bio = "I'm weeee"
		twitter = "zenathark"
		github = "zenathark"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		
		copyright = [
			"&copy; Juan Carlos Gal치n Hern치ndez"
		]
	
	[params.about]
		hide = false
		title = "Ipsum"
		content = "weouotuh"

	[params.portfolio]
		hide = false
		title = "Publications"
		
		[[params.portfolio.gallery]]
			title = "<a href="#"> Lorem ipsum </a>"
			description = "laralalala"

	[params.contact]
		hide = false
		title = "Get In Touch"
		content = "UAOEUOEUAIOUAE"

		address = [
		        "Sta. Catarina Martir",
		        "San Andres Cholula, Puebla, C.P. 72810",
			"Mexico"
                ]

		phone = "000-000-0000"

		email = "juan.galan@udlap.mx"

		[params.contact.form]
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url = "post/"
	weight = 10
