#+begin_export html
+++
categories = []
date = "2017-06-19T17:13:23-05:00"
tags = ["Writing Journal"]
title = "Writer's Journal #1"

+++
#+end_export

* Outcomes Reflection
  The Arizona State University offers a course through [[edx.org]] called *ENG101
  English Composition*.
  
  I decided to take this course in order to improve my writing skills overall.
  As researcher, most of my work is published on technical journals that require
  an specific structure that for us who english is our second language is easy
  to follow. However, I have found that while is easy to just blindly follow the
  classic technical writing style, in order to write high quality papers I have
  to be aware of how I do my writing.

  While searching for a writing course I had two objectives: must be a course
  given in English by native English speaker instructors, and it must have a
  broad series of objectives that can be applied on technical writing but also
  on different types of writing. My first objective is aimed to gain insight
  into the use of the written English language. My second objective is aimed to
  improve my technical writing by contrasting its structure with other writing
  styles. Also, it will allow me to write other kind of academic and non
  academic material.
  
  What I like about the *ENG101* course so far is its four objectives:
  + Rhetorical Knowledge
  + Critical Thinking
  + Process
  + Knowledge of Conventions
  
** Rhetorical Knowledge
   /Rhetoric/ is defined as "The art of effective or persuasive speaking or
   writing, especially the exploitation of figures of speech and other
   compositional techniques." Oxford Living Dictionaries, 2017. This was the
   most attractive objective. It is also one of the most difficult objectives to
   achieve for me.

   In order to fulfill this objective, I must learn how different genres are
   composed and consumed. I think that this is a very subjective matter as I
   also have to think how readers will react to the way the text is written. A
   surprising element of this objective is how different media is integrated
   on. As a computer scientist I am used to deal with usability and user
   experience elements on software design. However, I never realized that
   writing content must also be shaped differently.

** Critical Thinking, Reading and Composing.
   This was the most confusing objective. Maybe because I have used the term
   /Critical Thinking/ in a more restrictive way. The current description
   of the objective is as follows:

   #+begin_quote
   + Use composing and reading for inquiry, learning, critical thinking, and 
     communicating in various rhetorical contexts.
   + Read a diverse range of texts, attending especially to relationships 
     between assertion and evidence, to patterns of organization, to the 
     interplay between verbal and nonverbal elements, and to how these features 
     function for different audiences and situations.
   + Locate and evaluate (for credibility, sufficiency, accuracy, timeliness, 
     bias and so on) primary and secondary research materials, including 
     scholarly and professionally established and maintained databases or 
     archives, and informal electronic networks and internet sources.
   + Use strategies--such as interpretation, synthesis, response, critique, and 
     design/redesign--to compose texts that integrate the writer's ideas with 
     those from appropriate sources.
   #+end_quote

   The first time I read this objective I evoked the [[https://en.wikipedia.org/wiki/Scientific_method][Scientific Method]]. After a
   little bit of research on the meaning and use of the term of /Critical
   Thinking/, I have come to the conclusion that critical thinking can bee seen
   as either part of the /Scientific Method/ or a smaller version of it. As
   critical thinking only focuses on the evaluation and analysis of an issue
   (Oxford Living Dictionaries, 2017).

** Process.
   The course aims for teaching the different steps for producing a writing. In
   my experience, one of the hardest elements is rereading. When rereading my
   own work, I often neglect the flow or leave key definitions out because my
   familiarity with my own work makes me forget that my readers not necessarily
   have all definitions of a particular subject in mind. I found interesting
   that this objective also aims to teach collaborative and social aspects of
   writing.

** Knowledge of Conventions
   To know conventions on writing is extremely helpful. Even when I had no
   formal instruction on the English language, knowing basic conventions allowed
   me to write full papers without much hassle. While conventions is not a
   substitute of mastering a language, it can give a starting point and a
   general overview of a given genre. I'm looking forward to learn about
   different mechanics and formats.
   
While I already am familiarized with academic writing, having its elements defined
formally is of invaluable help when assesing the quality of my own writing. I think
academic writing must be unambiguous but also easy to digest.
