#+begin_export html
+++
categories = ["Writing Journal"]
date = "2017-06-21T18:40:40-05:00"
tags = ["Writing"]
title = "Self-Reflective Writing (WJ #3)"

+++
#+end_export
Writing is an iterative process. Assessing the quality is an important part of
any iterative process. This is as true in Software Engineering as it is in
Writing.  One way to improve the quality of any activity that builds something
is to edit it and re-do the parts that have little purpose. This superfluous
elements can potentially degrade the flow. However, self-editing and rewriting
is a tough process. It requires to detach ourselves from our writing and assess
it as a reader.

** Reflection on your writing 
Reflecting over our own writing process can help in the self-editing
process. One must spot inconsistencies or weak spots in our writing. By
reviewing our intentions, identifying our target audience, our decisions and our
overall writing process can help to spot elements that feel out of place or
pieces of writing that don't help to achieve our initial goals. Also, our goals
might be out of focus, hence our writing will potentially end up all over the
place making it an unsavory experience for our readers. Having well defined
goals will help us to create an engaging experience.  This can be achieved by
reviewing our goals introspectively when re-reading our work.
Reflective writing differs from other types of writing in the way that it
contains the feelings and intentions of the author. It is a search for the true
meaning of what we want to write. In a way, it is an egoist way of writing.

** Where reflective writing fits on the writing process
I see reflective writing as part of /Critical Thinking, Reading and Composing/
objective. As reflection is a strategy for composing well crafted texts. While
it may be seen as part of the process of writing, the third objective, it allows
to analyze objectively our work.

** Integrating reflective writing to my own work
After reading /Reflective Writing and the Revision Process: What Were You
Thinking?/ by Sandra L. Giles [fn:writing]. I realized about the importance of
re-reading my work with more criticism. Reviewing previous writing I come to the
realization that I never questioned my intentions behind my rhetorical
decisions. Not in my academic work neither in other written pieces. On this
course, I'd like to reflect about my whole writing process that, to be honest, is
not very thoughtful. A particular element I'll pay more attention is in how I
narrow a topic without derailing into other less important subjects for that
particular piece. Also, I want to be more reflective about how I want to engage
my readers. Each piece of writing may benefit from reflective writing.

** References

[fn:writing] Zemliansky, Pavel and Lowe, Charles, /Writing Spaces: Readings on Writing/, vol. 2, Parlor Press, 2010.
