#+begin_export html
+++
categories = ['Writing Journal' ]
date = "2017-06-22T18:17:23-05:00"
tags = ['Writing','Collaborative']
title = "Reflecting on Collaboration (WJ #4)"

+++
#+end_export

Collaborative working is present in all aspects of our life. From school work to
our jobs to our home. Learning to work with others is a fundamental skill in our
society. Collaborate with others on a project may allow to achieve better
results and be more productive than working individually. Some benefits from
collaboration are: Sinergy, Community Awareness, Share resources, Overcome of
Obstacles, Avoid Duplication, Access to funding sources (“Benefits of
Collaboration” 1).

Writing is no exception. By collaborating with others on a writing project why
can benefit from other’s people experience for our writing or help others to
improve their work. Having someone to review your writing like a “Beta reader”
or a “Critique Partner” may help you find what works and what doesn’t (Moreci,
Jenna).

“Collaborative writing can have two major forms: co-authoring and peer response”
Roen, Duane. The most challenging of the two forms of collaborative writing is
peer response. Showing your work to others is intimidating, mostly when your
peers have more experience than you like a teacher or and advisor. Most
postgraduate students struggle with his in its academic writing. When writing a
paper, postgraduate students must go through a series of revisions. This
revision process can become frustrating because most students feel that they
will let down his advisor or that they will be seen as not worthy. However, peer
response is a very important part to ensure and improve the quality of the
paper. An important part of collaborative writing is to learn to handle
criticism as a tool for improvement.

** References
1. Roen, Duane. “Writing as Collaboration”, ENG101x, 2016.
2. Moreci, Jena. “What is a Critique Partner”, 21 Sep. 2016, https://youtu.be/U1KJoXwgB3M.
